### ISSUE TITLE
Why is this needed?

### ISSUE THREAD

**Issue by davidak** [samuela/nixpkgs-upkeep#4] opened 2020-12-27 10:43 UTC
This question is not answered in the readme, so i just ask. Please add that information.

There is https://github.com/ryantm/nixpkgs-update and it runs on the community infrastructure. Why not contribute to it when it don't work for you and create another project instead?

**Comment by samuela** [comment] 2020-12-27 21:02
This is discussed here: https://discourse.nixos.org/t/ann-nixpkgs-upkeep-update-bot/8995.

The short answer is two-fold: I was not aware of nixpkgs-update when I created nixpkgs-upkeep and nixpkgs-update does not maintain the packages that I'd like updated.

**Comment by samuela** [comment] 2020-12-28 06:34
I'm going to close this as it's not a bug, but we can continue to discuss.

**Closed by samuela** 2020-12-28 06:34 UTC
